#server config
server:
  port: 8080

#db config #redis config
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/cerp?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&enabledTLSProtocols=TLSv1.2
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root@123}
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    port: 6379
    timeout: 10000
  cache:
    redis:
      cache-null-values: false
      use-key-prefix: true
      key-prefix: cerp
      time-to-live: 60000
      template.defaultSerializer: org.springframework.data.redis.serializer.GenericJackson2JsonRedisSerializer


logging :
level :
org.springframework.web : DEBUG


