#server config
server:
  port: 8080

#db config
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/cerp?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&enabledTLSProtocols=TLSv1.2
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root@123}
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update


logging :
level :
org.springframework.web : DEBUG


